name: RX 6750 XT Price Tracker

on:
  schedule:
    - cron: "0 */2 * * *"

  workflow_dispatch:

jobs:
  tracker:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"

    - name: Install packages
      run: |
        pip install requests beautifulsoup4

    - name: Run tracker
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USER_ID: ${{ secrets.DISCORD_USER_ID }}

      run: |
        python RX6750XT_Notifier.py
